-- Alle Vorgaben-Vorlagen erzeugen
INSERT IGNORE INTO GymAbi.Gost_Klausuren_Vorgaben
(Abi_Jahrgang,Halbjahr,Fach_ID,KursartAllg,Quartal,Dauer,Auswahlzeit,IstMdlPruefung,IstAudioNotwendig,IstVideoNotwendig,Bemerkungen) VALUES
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',1,255,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'LK',2,255,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',1,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'BI'),'GK',2,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',1,255,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'LK',2,255,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',1,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'CH'),'GK',2,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,90,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,100,0,0,0,0,'Vergleichsklausur'),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'D'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',1,180,0,1,1,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',1,225,0,1,1,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,90,0,1,1,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',2,90,0,0,0,0,'evtl. wenige wegen mündl. Prüfung E/F'),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',2,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,135,0,1,1,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,135,0,1,1,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'E'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'EK'),'GK',2,180,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'ER'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',1,180,0,1,1,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',2,225,0,1,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,90,0,1,1,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',2,90,0,0,0,0,'evtl. wenige wegen mündl. Prüfung E/F'),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',2,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,135,0,1,1,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',2,135,0,1,1,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'F'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'GE'),'GK',2,180,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',1,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'GK',2,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',1,255,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'IF'),'LK',2,255,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KR'),'GK',2,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',1,180,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'KU'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,90,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'L'),'GK',2,180,45,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',1,255,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'LK',2,255,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,90,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,100,0,0,0,0,'Vergleichsklausur'),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',1,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'M'),'GK',2,180,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'MU'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PA'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',1,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',2,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',1,255,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'LK',2,255,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',1,90,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',2,90,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',1,180,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PH'),'GK',2,180,0,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'PL'),'GK',2,180,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,90,0,1,1,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',2,90,0,1,1,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',2,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,135,0,1,1,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,135,0,1,1,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'S0'),'GK',2,180,30,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',1,180,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',2,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',1,180,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',2,180,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',1,225,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',2,225,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',1,255,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'LK',2,255,30,0,0,0,NULL),
	 (-1,0,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',2,90,0,0,0,0,NULL),
	 (-1,1,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',1,90,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',1,135,0,0,0,0,NULL),
	 (-1,2,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',2,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',1,135,0,0,0,0,NULL),
	 (-1,3,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',2,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',1,135,0,0,0,0,NULL),
	 (-1,4,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',2,135,0,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',1,180,30,0,0,0,NULL),
	 (-1,5,(SELECT ID FROM EigeneSchule_Faecher esf WHERE FachKrz = 'SW'),'GK',2,180,30,0,0,0,NULL);

-- Klausurvorgaben für aktuelle EF, Q1 und Q2 erzeugen
FOR i IN 0..5 DO
	INSERT IGNORE
		INTO Gost_Klausuren_Vorgaben 
		(Abi_Jahrgang, Halbjahr, Fach_ID, KursartAllg, Quartal, Dauer, Auswahlzeit, IstMdlPruefung, IstAudioNotwendig, IstVideoNotwendig, Bemerkungen)
		SELECT (
			SELECT Jahr 
			FROM Schuljahresabschnitte s 
			WHERE ID = (SELECT Schuljahresabschnitts_ID FROM EigeneSchule es)) + 2 - TRUNCATE(i/2,0), 
		Halbjahr, 
		Fach_ID, 
		KursartAllg, 
		Quartal, 
		Dauer, 
		Auswahlzeit, 
		IstMdlPruefung,
		IstAudioNotwendig, 
		IstVideoNotwendig, 
		Bemerkungen 
		FROM Gost_Klausuren_Vorgaben 
		WHERE Halbjahr = i;
END FOR;

-- Kursklausuren für aktuelle EF, Q1 und Q2 erzeugen
FOR i IN 0..5 DO
	INSERT IGNORE 
		INTO Gost_Klausuren_Kursklausuren -- Erzeuge Kursklausuren für Q2.1.1
		(Vorgabe_ID, Kurs_ID)
		SELECT (
			SELECT ID 
			FROM Gost_Klausuren_Vorgaben kv 
	 		WHERE Abi_Jahrgang = (SELECT Jahr FROM Schuljahresabschnitte s WHERE ID = (SELECT Schuljahresabschnitts_ID FROM EigeneSchule es)) + 2 - TRUNCATE(i/2,0)
				AND Halbjahr = i
				AND KursartAllg = k.KursartAllg 
				AND Quartal = i % 2 + 1
				AND kv.Fach_ID = k.Fach_ID),
		ID 
		FROM Kurse k 
		WHERE Schuljahresabschnitts_ID = (
			SELECT ID 
			FROM Schuljahresabschnitte s 
			WHERE ID = (SELECT Schuljahresabschnitts_ID FROM EigeneSchule es))
		AND ASDJahrgang = (CASE WHEN i<=1 THEN "EF" WHEN i >= 4 THEN "Q2" ELSE "Q1" END)
 		AND (Fach_ID, KursartAllg) IN ( -- Nur Fachkombinationen, für die es Vorgaben gibt
			Select Fach_ID, KursartAllg 
			FROM Gost_Klausuren_Vorgaben gkv);
END FOR;

-- Schülerklausuren für aktuelle EF, Q1 und Q2 erzeugen
FOR i IN 1..2 DO
	INSERT IGNORE
		INTO Gost_Klausuren_Schuelerklausuren 
	 	(Schueler_ID, Kursklausur_ID)
	 	SELECT s.ID, (
 			SELECT gkk.ID 
 			FROM Gost_Klausuren_Kursklausuren gkk 
 				JOIN Gost_Klausuren_Vorgaben gkv ON gkk.Vorgabe_ID = gkv.ID 
	 		WHERE Kurs_ID = k.id 
 				AND Quartal = i
 			)
		FROM SchuelerLernabschnittsdaten sa 
    		JOIN SchuelerLeistungsdaten sl on  sl.Abschnitt_ID = sa.id 
    		JOIN Schueler s on sa.Schueler_ID = s.ID  
		    JOIN Kurse k on k.id = sl.Kurs_ID
		    JOIN Gost_Klausuren_Kursklausuren gkk ON gkk.Kurs_ID = k.ID
	    	JOIN Gost_Klausuren_Vorgaben gkv2 ON gkk.Vorgabe_ID = gkv2.ID  
		WHERE s.Status = 2 
			AND Quartal = i
			AND s.Geloescht <> '+' # nur aktive Schueler des aktuellen Schuljahresabschnittes berücksichtigen
	    	AND (
	    		sl.Kursart in ('LK1','LK2','AB3','AB4','GKS') # nur schriftliche Belegungen beruecksichten
		    	AND Halbjahr < 5
		    	OR sl.Kursart in ('LK1','LK2','AB3') # nur schriftliche Belegungen beruecksichten
	    		AND Halbjahr = 5 # in Q2.2 nicht AB4 und GKS
	    	) AND (k.Fach_ID, k.KursartAllg) IN ( -- Nur Fachkombinationen, für die es Vorgaben gibt
 				SELECT Fach_ID, KursartAllg 
 				FROM Gost_Klausuren_Vorgaben gkv)
    ;
END FOR;